name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:

  build:
    strategy:
      matrix:
        toolchain: [stable, nightly]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt update
    - run: sudo apt install ffmpeg -y # Install ffmpeg for ffprobe, so issue #39 test can pass
    - run: rustup default ${{ matrix.toolchain }}
    - run: rustup update
    - run: cargo build
    - run: cargo test

  style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: cargo fmt -- --check
    - run: cargo clippy

  conventional-commits:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: pip3 install -U Commitizen
      # The commit hash here is that of the commit where we started using conventional commits.
    - run: cz check --rev-range 16610ddb..HEAD
