name: Deploy

on:
  push:
    tags:
    - 'v*'

jobs:

  ci:
    uses: ./.github/workflows/ci.yml

  cargo-publish:
    runs-on: ubuntu-latest

    needs:
      - ci

    steps:
    - uses: actions/checkout@v3
    - run: cargo publish --token ${CRATES_TOKEN}
      env:
        CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
